name: Feature request
description: Propose new user-facing functionality
title: "feat: "
labels: ["type: feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What user problem does this solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      value: |
        - [ ] 
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      value: |
        - [ ] 
    validations:
      required: true
  - type: input
    id: epic
    attributes:
      label: Parent epic
      placeholder: "#65"
